- hosts: "{{ ansible_hosts }}"
  tasks:
    - name: Add TimberIO apt GPG key
      apt_key:
        url: https://packagecloud.io/timberio/packages/gpgkey
    - name: Add TimberIO package repository
      apt_repository:
        repo: deb https://packagecloud.io/timberio/packages/ubuntu/ bionic main
    - name: Create vector group # systemd file included with Vector specifies that it be run as vector/vector, but the package does not create a vector group
      group:
        name: vector
        state: present
    - name: Create users
      user:
        state: present
        name: "{{ item }}"
        shell: /bin/bash
      loop:
        - vidfeeder
        - vector
    - name: Install packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - nginx
          - python3-boto3
          - vector
    - name: Create Directories
      file:
        state: directory
        recurse: true
        path: "{{ item }}"
      loop:
        - /home/vidfeeder/.aws
        - /home/vector/.aws
        - /home/vidfeeder/.ssh
        - /opt/vector/bin
    - name: Copy authorized_keys
      shell: cp /root/.ssh/authorized_keys /home/vidfeeder/.ssh
    - name: Change authorized_keys permissions
      file:
        state: file
        path: /home/vidfeeder/.ssh/authorized_keys
        owner: vidfeeder
        group: vidfeeder
        mode: 0600
    - name: Copy sudoers
      template:
        src: templates/sudoers.j2
        dest: /etc/sudoers
        validate: '/usr/sbin/visudo -cf %s'
    - name: Copy Templates
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
          - {
              src: 'templates/aws_credentials.j2',
              dest: '/home/vidfeeder/.aws/credentials'
            }
          - {
              src: 'templates/aws_credentials.j2',
              dest: '/home/vector/.aws/credentials'
            }
          - {
              src: 'templates/nginx.conf.j2',
              dest: '/etc/nginx/nginx.conf'
            }
          - {
              src: 'templates/vector.toml.j2',
              dest: '/etc/vector/vector.toml'
            }
    - name: Symlink /opt/vector/bin/vector
      file:
        src: /usr/bin/vector
        dest: /opt/vector/bin/vector
        state: link
    - name: Enable and restart services
      systemd:
        name: "{{ item }}"
        state: restarted # Never idempotent, always restarts
        enabled: yes
      loop:
        - nginx
        - vector
